spring.application.name=ms-pedidos
server.port=8084

spring.datasource.url=jdbc:mysql://localhost:3306/prueba3?createDatabaseIfNotExist=true&serverTimezone=UTC
spring.datasource.username=${DB_USER:root}
spring.datasource.password=${DB_PASSWORD:}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
app.validar-servicios-externos=${VALIDAR_SERVICIOS_EXTERNOS:false}
servicios.usuarios.url=${MS_USUARIOS_URL:http://localhost:8081}
servicios.productos.url=${MS_PRODUCTOS_URL:http://localhost:8082}

logging.level.cl.duoc.fullstack.mspedidos=INFO
