server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      routes:
        # Ruta para el Microservicio de Productos
        - id: productos-route
          uri: lb://MS-PRODUCTOS
          predicates:
            - Path=/api/v1/productos/**
          filters:
            - StripPrefix=2

        # Ruta para el Microservicio de Inventario
        - id: inventario-route
          uri: lb://MS-INVENTARIO
          predicates:
            - Path=/api/v1/inventarios/**
          filters:
            - StripPrefix=2

        # Rutas del Microservicio de Pedidos
        - id: pedidos-route
          uri: lb://MS-PEDIDOS
          predicates:
            - Path=/api/v1/pedidos/**,/api/v1/detalles-pedido/**,/api/v1/hateoas/pedidos/**

        # Rutas del Microservicio de Pagos
        - id: pagos-route
          uri: lb://MS-PAGOS
          predicates:
            - Path=/api/v1/pagos/**,/api/v1/hateoas/pagos/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: true

logging:
  level:
    org.springframework.cloud.gateway: DEBUG