# puerto pa  corra esta cosa
server.port=8081
spring.application.name=ms-usuarios

# conexion al laragon (bd prueba1 segun la guia)

spring.datasource.url=jdbc:mysql://localhost:3306/prueba1?createDatabaseIfNotExist=true&useSSL=false
spring.datasource.username=root
# en laragon la clave viene vacia, si falla le pongo root o admin despue
spring.datasource.password=

#
spring.jpa.hibernate.ddl-auto=update

#  querys en la consola
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true