spring.application.name=ms-envios
server.port=8086

spring.datasource.url=jdbc:mysql://localhost:3306/prueba5?createDatabaseIfNotExist=true&serverTimezone=UTC
spring.datasource.username=${DB_USER:root}
spring.datasource.password=${DB_PASSWORD:}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

spring.liquibase.enabled=true
spring.liquibase.change-log=classpath:db/changelog/db.changelog-master.yaml
app.validar-servicios-externos=${VALIDAR_SERVICIOS_EXTERNOS:false}
servicios.pedidos.url=${MS_PEDIDOS_URL:http://localhost:8084}
servicios.usuarios.url=${MS_USUARIOS_URL:http://localhost:8081}

logging.level.cl.duoc.fullstack.msenvios=INFO
